package enums;

public enum State {
    INIT_STATE,
    LOGIN_STATE,
    CREATE_ACCOUNT_STATE,
    CUSTOMER_STATE,
    PROFILE_STATE,
    SELECT_STATE,
    ORDER_VIEW_STATE,
    CATEGORY_STATE,
    BRAND_STATE,
    PRODUCT_STATE,
    LIST_STATE,
    PRODUCT_SELECTION_STATE,
    CART_STATE,
    LIST_PRODUCT_STATE,
    SELECTED_ORDER_STATE,
    CHANGE_ADRESS_STATE,
    CHANGE_PASSWORD_STATE,
    CHANGE_EMAIL_STATE
}
